# Generated by Django 5.1.7 on 2026-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], max_length=10),
        ),
    ]
